---
- name: test filter
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    input_string: "482056876421"
  tasks:
    - name: debug
      debug:
        msg: "{{ input_string | filter_function }}"
