apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-robot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-robot
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-robot
subjects:
- kind: ServiceAccount
  name: job-robot # Name of the ServiceAccount
roleRef:
  kind: Role # This must be Role or ClusterRole
  name: job-robot # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
