kind: Deployment
apiVersion: apps/v1
metadata:
  name: node-exporter-depl
  labels:
    app: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter
        ports:
        - containerPort: 9100
          protocol: "TCP"
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
spec:
  type: LoadBalancer
  selector:
    app: node-exporter
  ports:
    - protocol: "TCP"
      port: 9100
      targetPort: 9100
      nodePort: 30000